### ISSUE TITLE
Items Found Error Bug

### ISSUE THREAD

**Issue by CustomAmelia** [thurdev/roblox-limiteds-sniper-free#11]
i'm getting this weird bug where it detects that there's items available but there aren't and then it spams Could not get item details {"code":0,"message":"Token Validation Failed"} and then tries to buy items and then gives me an error, here's the whole log : 

```
C:\Users\user\Desktop\roblox-limiteds-sniper-free-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:61
        _Callback_error.set(this, new Errors_js_1.ProtocolError());
                                  ^

ProtocolError: Protocol error (Page.navigate): Invalid parameters Failed to deserialize params.url - BINDINGS: mandatory field missing at position 50
    at new Callback (C:\Users\user\Desktop\roblox-limiteds-sniper-free-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:61:35)
    at CallbackRegistry.create (C:\Users\user\Desktop\roblox-limiteds-sniper-free-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:106:26)
    at Connection._rawSend (C:\Users\user\Desktop\roblox-limiteds-sniper-free-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:216:26)
    at CDPSessionImpl.send (C:\Users\user\Desktop\roblox-limiteds-sniper-free-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:425:78)
    at navigate (C:\Users\user\Desktop\roblox-limiteds-sniper-free-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Frame.js:230:47)
    at Frame.goto (C:\Users\user\Desktop\roblox-limiteds-sniper-free-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Frame.js:208:13)
    at CDPPage.goto (C:\Users\user\Desktop\roblox-limiteds-sniper-free-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:438:91)
    at C:\Users\user\Desktop\roblox-limiteds-sniper-free-main\utils\roblox.js:17:20
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user\Desktop\roblox-limiteds-sniper-free-main\utils\roblox.js:5:58)

Node.js v19.9.0
```

**Comment by thurdev** [comment]
Probably because of your .env, but can you check the new version?

**Comment by thurdev** [comment]
Discontinued
